version: '3.7'
services:
  web:
    image: cjoakim/azure-cosmos-db-ts-web-prod
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data:rw
      - ./tmp:/tmp:rw
      - ./uploads:/uploads:rw
    environment:
      DEBUG:                               azure-cosmos-db-ts-web:*
      PORT:                                3000
      AZURE_WEB_AUTH_USERS:                $AZURE_WEB_AUTH_USERS
      AZURE_WEB_COOKIE_KEYS:               $AZURE_WEB_COOKIE_KEYS
      AZURE_WEB_COOKIE_AGE:                $AZURE_WEB_COOKIE_AGE
      AZURE_COSMOSDB_NOSQL_URI:            $AZURE_COSMOSDB_NOSQL_URI
      AZURE_COSMOSDB_NOSQL_RW_KEY1:        $AZURE_COSMOSDB_NOSQL_RW_KEY1
      AZURE_OPENAI_URL:                    $AZURE_OPENAI_URL
      AZURE_OPENAI_KEY1:                   $AZURE_OPENAI_KEY1
      AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT:  $AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT 
      AZURE_SEARCH_URL:                    $AZURE_SEARCH_URL
      AZURE_SEARCH_NAME:                   $AZURE_SEARCH_NAME
      AZURE_SEARCH_ADMIN_KEY:              $AZURE_SEARCH_ADMIN_KEY
      AZURE_SEARCH_QUERY_KEY:              $AZURE_SEARCH_QUERY_KEY
    command: node ./build/index.js

# docker compose -f docker-compose-web.yml up
# docker compose -f docker-compose-web.yml down
